// https://thestoryshack.com/tools/warrior-cat-name-generator/
const wordList1 = [
  "Brokenstalk",
  "Seedeyes",
  "Lailie",
  "Pigeonrock",
  "Acorn",
  "Sheba",
  "Turner",
  "Antback",
  "Jaggedsight",
  "Whitemist",
  "Darkflank",
  "Nimbus",
  "Alpine",
  "Clever Sky",
  "Zeit",
  "Aspenvine",
  "Ina",
  "Flash",
  "Edwina",
  "Eveningstream",
  "Beaverspring",
  "Badgerrunner",
  "Driftlight",
  "Ravenrunner",
  "Duskbrook",
  "Fawnspirit",
  "Lightsong",
  "Standingbriar",
  "Lightningpoppy",
  "Badgerear",
  " Runningflower",
  "Flyglow",
  "Ravenbelly",
  "Conand",
  "Thunderstorm",
  "Leafstar",
  "Smoke",
  "Swayne",
  "Smittens",
  "Shadowpatch",
  "Power",
];

// https://thestoryshack.com/tools/celestial-name-generator/
const wordList2 = [
  "Estrella",
  "Luminar",
  "Cordelia",
  "Estrella",
  "Zorah",
  "Vega",
  "Maia",
  "Aurorae",
  "Celestis",
  "Helionis",
  "Celestria",
  "Oberon",
  "Zenobia",
  "Aurorium",
  "Zenitha",
  "Heliosia",
  "Androm",
  "Cassiopea",
  "Fidelis",
  "Kael",
  "Nebulae",
  "Kya",
  "Phoenix",
  "Astrae",
  "Aurora",
  "Lyrisa",
  "Lyra",
  "Moonstonia",
  "Cygnus",
  "Callisto",
  "Lyrisa",
  "Hestia",
  "Nephria",
  "Hyperion",
  "Elysis",
  "Solestra",
  "Nebulonera",
  "Neith",
  "Naiad",
  "Nyx",
  "Aurorae",
  "Azuriel",
  "Zorah",
  "Uranessa",
  "Cometron",
  "Mordecai",
  "Aurorica",
];

export function generateUsername() {
  const firstWord = wordList1[Math.floor(Math.random() * wordList1.length)];
  const secondWord = wordList2[Math.floor(Math.random() * wordList2.length)];

  return firstWord + "_" + secondWord + Math.floor(Math.random() * 1234);
}
